CREATE TABLE	DimTimestep	(	TimestepKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			TimestepValue	VARCHAR(50))
CREATE TABLE	DimModelOtherParameters	(	ModelOtherParametersKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			ModelName	VARCHAR(50) NOT NULL,
			DeathRate	FLOAT DEFAULT 0 NOT NULL,
			BirthRate	FLOAT DEFAULT 0 NOT NULL,
			TransmissionRate	FLOAT DEFAULT 0 NOT NULL,
			DestructionRate	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimResurrectionRate	(	ResurrectionRateKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			ResurrectionRateValue	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimZombieWinRate	(	ZombieWinRateKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			ZombieWinRateValue	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimCriticalDistance	(	CriticalDistanceKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			CriticalDistanceValue	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimVelocity	(	VelocityKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			Mu	FLOAT DEFAULT 0 NOT NULL,
			Sigma	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimInitialPosition	(	InitialPositionKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			xinit	FLOAT DEFAULT 0 NOT NULL,
			yinit	FLOAT DEFAULT 0 NOT NULL)
CREATE TABLE	DimHumanoid	(	HumanoidKey	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
			HumanoidName	VARCHAR(50) NOT NULL,
			nSusceptible	FLOAT DEFAULT 0 NOT NULL,
			nZombie	FLOAT DEFAULT 0 NOT NULL,
			Ratio	FLOAT NOT NULL,
			RatioBand	VARCHAR(50) NOT NULL)